PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dm2e: <http://onto.dm2e.eu/schemas/dm2e/>
PREFIX dm2e11: <http://onto.dm2e.eu/schemas/dm2e/1.1/>

