SELECT ?host (COUNT(?host) AS ?no) {
    GRAPH ?g {
        {
            ?uri ?p1 ?o1 .
        }
        UNION
        {
            ?s1 ?p2 ?uri .
            FILTER(isIRI(?uri))
        }
    }
    BIND(STR(?uri) AS ?s)
    FILTER(! STRSTARTS(?s, "http://data.dm2e.eu"))
    BIND(STRBEFORE(SUBSTR(?s, 8), "/") AS ?host)
}
GROUP BY ?host
ORDER BY DESC(?no)
