# :Alice foaf:age "25".
# :Bob foaf:age "25" .
# :Charlie foaf:age "30 .
# =>
# ?predicate ?object ?no
# foaf:age "25" 2
# foaf:age "30" 1



SELECT ?predicate ?object (COUNT (*) AS ?no)
WHERE
{
    GRAPH ?g
    {
        ?s ?predicate ?object .
    }
}
GROUP BY ?predicate ?object
HAVING (?no > 1)
ORDER BY DESC(?no)
